settings:
  title: '状态监控'
  url: 'https://status.owdie.me' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有系统均在运行'
  notAllmonitorsOperational: '并非所有系统都在运行'
  monitorLabelOperational: '运行'
  monitorLabelNotOperational: '故障'
  monitorLabelNoData: '没有数据'
  dayInHistogramNoData: '没有数据'
  dayInHistogramOperational: '一切正常'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: owdie-me # unique identifier 
    name: Blog
    description: '为学日益，为道日损。' # default=empty
    url: 'https://owdie.me/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: embykeeper
    name: Embykeeper
    description: 'Hello World'
    url: 'https://embykeeper-k7n5.onrender.com'
    method: GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: nezha-owdie-me
    name: 哪吒面板
    description: 'VPS状态监控'
    url: 'https://nezha.owdie.me'
    method: GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: audiences-me
    name: Audiences
    description: 'Hello World'
    url: 'https://audiences.me'
    method: GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: hdchina
    name: HDChina
    description: 'Hello World'
    url: 'https://hdchina.org'
    method: GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
